spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: cobre-notification-platform
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 10
  flyway:
    enabled: true
  mvc:
    problemdetails:
      enabled: true

notifications:
  json-import:
    enabled: ${NOTIFICATION_JSON_IMPORT_ENABLED:false}
    location: classpath:imports/notification_events.json
  security:
    clients:
      - client-id: CLIENT001
        token: ${NOTIFICATION_CLIENT_001_TOKEN:}
      - client-id: CLIENT002
        token: ${NOTIFICATION_CLIENT_002_TOKEN:}
      - client-id: CLIENT003
        token: ${NOTIFICATION_CLIENT_003_TOKEN:}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
